### ISSUE TITLE
Background gradient not covering the entire height of the content

### ISSUE THREAD

**Issue by curator69** [princid/Expense-Tracker#1]

**Comment by Akamourya18** [comment]
Can you please describe more about the issue. Which page is being referred here?

**Comment by curator69** [comment]
for starter, the login page, don't know about the other pages, as i don't have the login details

**Comment by princid** [comment]
Hey! @curator69 , You can register with any E-mail and then you can Login with your Login Credentials and can explore further pages as well

**Comment by princid** [comment]
@curator69, Can you describe more about the issue you have raised?

**Comment by curator69** [comment]
> Hey! @curator69 , You can register with any E-mail and then you can Login with your Login Credentials and can explore further pages as well

okay

**Comment by curator69** [comment]
![Screenshot (99)](https://user-images.githubusercontent.com/75662004/194770678-6c4ba73f-06c2-43c3-b432-1c5447a5b010.png)

**Comment by princid** [comment]
Thanks for raising the issue, you can go ahead and make a pull request.

**Comment by curator69** [comment]
can u assign the issue to me?

**Comment by princid** [comment]
Yeah Sure!

**Comment by curator69** [comment]
thanx
