### ISSUE TITLE
Create a Contribution.md file

### ISSUE THREAD

**Issue by YashM246** [princid/Expense-Tracker#14]

**Comment by YashM246** [comment]
Hey I could work on this. Could you assign this to me?

**Comment by princid** [comment]
Can you please elaborate the issue?

**Comment by YashM246** [comment]
Basically add a contribution.md file for the people who are new to Open Source Contributions and participating in Hacktoberfest.

**Comment by princid** [comment]
Sure @YashM246 go ahead!

**Comment by YashM246** [comment]
I'll start working on it right away

**Comment by YashM246** [comment]
@princid I have added a pull request. Please look into it. Thanks!
