### ISSUE TITLE
[Enhancement] Field basic validation on add/edit transaction

### ISSUE THREAD

**Issue by anil-muraleedharan** [princid/Expense-Tracker#25]
Currently if any of the fields of the add/edit transaction form was empty while submitting the form there will be a error message shown in the top as "Something went wrong" as shown below since the backend server sends a 500.

<img width="652" alt="Screenshot 2022-10-17 at 12 28 05 AM" src="https://user-images.githubusercontent.com/56071561/196053164-64f14166-3066-49f2-b475-0fbc67e675ca.png">

It would be better if we could show a specific error dialog with a proper message which helps the users know which field was invalid without sending a request to the backend server.

Attaching a screenshot of the expected error dialog window

<img width="621" alt="Screenshot 2022-10-17 at 12 25 00 AM" src="https://user-images.githubusercontent.com/56071561/196053275-76308b16-33b6-402b-8c8a-eb5c8197402e.png">

**Comment by anil-muraleedharan** [comment]
@princid could you review this suggestion, if it seems valid please add required labels and I would like to work on this issue.
Also would like to get your suggestions on the message as well as which are the required fields

**Comment by anil-muraleedharan** [comment]
@princid the development for this enhancement is almost done if you could help me with the mandatory fields and default values for non mandatory fields I could commit and raise a PR for this

**Comment by princid** [comment]
Well done man! Go ahead and make a pull request.

**Comment by anil-muraleedharan** [comment]
@princid, I have raised a [PR](https://github.com/princid/Expense-Tracker/pull/28) for this issue please review it whenever possible. Thank you :)
