### ISSUE TITLE
[ Enhancement ] Ask for confirmation before deleting a transaction

### ISSUE THREAD

**Issue by anil-muraleedharan** [princid/Expense-Tracker#27]
Currently if we click delete button for a transaction it directly gets deleted. It would be better if we could have a kind of confirmation asked from the user if they are sure about the deletion. It would prevent the user from accidentally deleting a transaction.

**Comment by anil-muraleedharan** [comment]
@princid could you take a look at this enhancement. If you feel this is a valid issue please add the required labels and feel free to share any suggestions regarding this.

**Comment by princid** [comment]
Sure! that's a good idea actually.

**Comment by anil-muraleedharan** [comment]
@princid I have a raised a [PR](https://github.com/princid/Expense-Tracker/pull/29) for this issue please review it whenever you have time

**Comment by anil-muraleedharan** [comment]
@princid I have noticed this PR have been reverted #29 , any specific reason for that ?
