### ISSUE TITLE
Minor Ui Changes

### ISSUE THREAD

**Issue by smrkarkii** [princid/Expense-Tracker#3]
1. Changing of color can be added while hovering over the links  "Click here to register" and "Click here to login".
2. Some effects should be added while hovering over the buttons like login, register and logout buttons.
3. The spelling of expense is mistake.
Please assign this issue to me under hacktoberfest.
![grammar](https://user-images.githubusercontent.com/58778838/194770557-0aa74eb0-2a0b-4410-bbf9-e674ef1dd34a.png)
![Screenshot 2022-10-09 230444](https://user-images.githubusercontent.com/58778838/194770559-c07d8440-49d6-4c87-a222-6e95cd4c2059.png)

**Comment by princid** [comment]
Sure, go ahead!

**Comment by smrkarkii** [comment]
Thanks
