### ISSUE TITLE
[Enhancement] Adding an indication for mandatory fields in the add/edit transaction form

### ISSUE THREAD

**Issue by pssruthy** [princid/Expense-Tracker#30]
When the user try to add/ edit a new transaction with a few fields being empty like below, user will be getting a validation error to fill the mandatory fields. It would be better if we could add an indicator like * to represent mandatory fields.

<img width="541" alt="Screenshot 2022-10-18 at 9 54 19 PM" src="https://user-images.githubusercontent.com/58027046/196488850-e7f712bf-0875-4a07-b90d-5585a7a34ef3.png">

<img width="500" alt="Screenshot 2022-10-18 at 9 54 26 PM" src="https://user-images.githubusercontent.com/58027046/196488902-81cdf6f4-76dd-4313-9e40-571b4152b31b.png">

**Comment by pssruthy** [comment]
@princid could you review this suggestion and add the required labels?

**Comment by princid** [comment]
@pssruthy Sure! Go ahead.
