### ISSUE TITLE
[ Bug ] Deployed application is failing

### ISSUE THREAD

**Issue by anil-muraleedharan** [princid/Expense-Tracker#39]
Noticed that [deployed version](https://expense-tracker-psg.herokuapp.com/) of our application is failing.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/56071561/197949547-dd75379f-e351-439c-963e-473394c824e1.png">

Could not what is the error occurring

**Comment by anil-muraleedharan** [comment]
@princid could you take a look at the logs for this issue
If possible please share the screenshot of the logs

**Comment by princid** [comment]
Yeah! Actually I'm also not being able to understand this issue.

**Comment by anil-muraleedharan** [comment]
@princid you will be able to see the logs from heroku, if you could share the logs from heroku here I might be able to help to understand the issue

**Comment by princid** [comment]
![image](https://user-images.githubusercontent.com/90444477/197986690-cf5c79e1-4983-4f85-932d-66df98b2f202.png)

**Comment by princid** [comment]
@anil-muraleedharan will it be enough? Or do I need to share anything else? Kindly let me know, and Thanks in advance.

**Comment by anil-muraleedharan** [comment]
@princid It does not seem to have any specific information about the failure, shall we connect for a short call through zoom today evening so that we could try to debug this issue?
Please suggest some time after 6 when you will be available.

**Comment by princid** [comment]
Can we do it on Saturday?
