### ISSUE TITLE
User not redirected to home page after signup

### ISSUE THREAD

**Issue by DevoAbhi** [princid/Expense-Tracker#6]
After signup, user stays in the register page. 

Can I be assigned for this task?

**Comment by princid** [comment]
Because after resgistration, user needs to Login first. You can do one thing, that when user registers himself it redirects to the Login Page.

**Comment by DevoAbhi** [comment]
Ok, I can do that. 
Can you assign me please and give a hacktoberfest label to this issue?

**Comment by princid** [comment]
Sure man! Go ahead....
